# Generated by Django 4.2.23 on 2025-08-29 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('traj_a', models.JSONField()),
                ('traj_b', models.JSONField()),
                ('choice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
