# Generated by Django 4.2.23 on 2025-08-29 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reinforce', 'Baseline REINFORCE'), ('reward', 'Reward (Bradley–Terry)'), ('rlhf', 'RLHF fine-tune')], max_length=16)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('logs', models.TextField(blank=True, default='')),
            ],
        ),
    ]
